[phases.setup]
nixPkgs = ["openssl"]

[phases.install]
cmds = ["npm install -g pnpm@9.15.0", "pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter @mrtpvrest/database exec prisma generate"]

[start]
cmd = "node src/index.js"
